# Jekyll Resume Theme

# Site settings
title: Ruibin Zhou - Computer Game Engineering MSc
email: zhouruibin0730@gmail.com
description: Ruibin's digital resume made by Jekyll.
baseurl: ""
url: "http://joooseph0730.github.io"
name: Ruibin Zhou
job: front end engineer
location: Newcastle Upon Tyne, UK
languages: HTML, CSS and Javascript
twitter_username: 
github_username:  Joooseph0730
codepen_username:  
email_address: zhouruibin0730@gmail.com

# Build settings
markdown: kramdown
