# Jekyll Resume Theme

# Site settings
title: Ruibin Zhou - Computer Game Engineering MSc
email: zhouruibin0730@gmail.com
description: Ruibin's digital resume made by Jekyll.
baseurl: ""
url: "http://joooseph0730.github.io"
name: Ruibin Zhou
job: Computer Game Engineering Student
location: Newcastle Upon Tyne, UK
languages: C++
twitter_username: 
github_username:  Joooseph0730
linkedin_username: ruibin-zhou-887008183
codepen_username:  
email_address: zhouruibin0730@gmail.com

# Build settings
markdown: kramdown
